apiVersion: v1
kind: Pod
metadata:
  name: task-7
  annotations:
    deps: task-6
spec:
  schedulerName: python-scheduler
  restartPolicy: Never
  containers:
  - name: task-7
    image: busybox
    command:
    - sh
    - -c
    - sleep 0.651
