apiVersion: v1
kind: Pod
metadata:
  name: task-2
  annotations:
    deps: task-1
spec:
  schedulerName: python-scheduler
  restartPolicy: Never
  containers:
  - name: task-2
    image: busybox
    command:
    - sh
    - -c
    - sleep 1.302
