apiVersion: v1
kind: Pod
metadata:
  name: task-4
  annotations:
    deps: task-3
spec:
  schedulerName: python-scheduler
  restartPolicy: Never
  containers:
  - name: task-4
    image: busybox
    command:
    - sh
    - -c
    - sleep 1.658
