apiVersion: v1
kind: Pod
metadata:
  name: task-39
  annotations:
    deps: task-37
spec:
  schedulerName: python-scheduler
  restartPolicy: Never
  containers:
  - name: task-39
    image: busybox
    command:
    - sh
    - -c
    - sleep 8.115
