apiVersion: v1
kind: Pod
metadata:
  name: task-8
  annotations:
    deps: task-7
spec:
  schedulerName: python-scheduler
  restartPolicy: Never
  containers:
  - name: task-8
    image: busybox
    command:
    - sh
    - -c
    - sleep 2.609
