apiVersion: v1
kind: Pod
metadata:
  name: task-35
  annotations:
    deps: task-34
spec:
  schedulerName: python-scheduler
  restartPolicy: Never
  containers:
  - name: task-35
    image: busybox
    command:
    - sh
    - -c
    - sleep 0.484
