apiVersion: v1
kind: Pod
metadata:
  name: task-1
  annotations:
    deps: task-0
spec:
  schedulerName: python-scheduler
  restartPolicy: Never
  containers:
  - name: task-1
    image: busybox
    command:
    - sh
    - -c
    - sleep 2.387
