apiVersion: v1
kind: Pod
metadata:
  name: task-25
  annotations:
    deps: task-24,task-23
spec:
  schedulerName: python-scheduler
  restartPolicy: Never
  containers:
  - name: task-25
    image: busybox
    command:
    - sh
    - -c
    - sleep 1.449
