apiVersion: v1
kind: Pod
metadata:
  name: task-23
  annotations:
    deps: task-20,task-22
spec:
  schedulerName: python-scheduler
  restartPolicy: Never
  containers:
  - name: task-23
    image: busybox
    command:
    - sh
    - -c
    - sleep 1.074
